/// Integration tests for backend-nodejs.
///
/// The backend emits 4 files:
///   files[0] = package.json
///   files[1] = tsconfig.json
///   files[2] = src/<module>.ts
///   files[3] = tests/roundtrip.test.ts

use std::path::PathBuf;
use backend_nodejs::NodeJsBackend;
use cddlc_codegen::{Backend, CodegenOptions};
use cddlc_ir::lower;
use cddlc_parser::parse_cddl;

// ── Helpers ───────────────────────────────────────────────────────────────────

struct GeneratedPackage {
    package_json: String,
    tsconfig:     String,
    source:       String,
    tests:        String,
}

fn compile(src: &str) -> GeneratedPackage {
    compile_with_opts(src, CodegenOptions::default())
}

fn compile_with_opts(src: &str, opts: CodegenOptions) -> GeneratedPackage {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let out     = NodeJsBackend.generate(&lowered.module, &opts).expect("generate");
    assert_eq!(out.files.len(), 4, "expected 4 output files");
    GeneratedPackage {
        package_json: out.files[0].content.clone(),
        tsconfig:     out.files[1].content.clone(),
        source:       out.files[2].content.clone(),
        tests:        out.files[3].content.clone(),
    }
}

// ── Package structure ─────────────────────────────────────────────────────────

#[test]
fn test_emits_four_files() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("t.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = NodeJsBackend.generate(&lowered.module, &opts).unwrap();
    assert_eq!(out.files.len(), 4);
    assert!(out.files[0].path.ends_with("package.json"));
    assert!(out.files[1].path.ends_with("tsconfig.json"));
    assert!(out.files[2].path.ends_with(".ts"));
    assert!(out.files[3].path.ends_with("roundtrip.test.ts"));
}

#[test]
fn test_crate_dir_named_after_module() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("sensor.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = NodeJsBackend.generate(&lowered.module, &opts).unwrap();
    assert!(out.files[0].path.starts_with("sensor-cbor/"));
    assert!(out.files[2].path.starts_with("sensor-cbor/src/"));
    assert!(out.files[3].path.starts_with("sensor-cbor/tests/"));
}

// ── package.json ──────────────────────────────────────────────────────────────

#[test]
fn test_package_json_generated_comment() {
    let g = compile("x = uint");
    assert!(g.package_json.contains("@generated by cddlc"));
}

#[test]
fn test_package_json_esm_type() {
    let g = compile("x = uint");
    assert!(g.package_json.contains("\"type\": \"module\""));
}

#[test]
fn test_package_json_cborg_dependency() {
    let g = compile("x = uint");
    assert!(g.package_json.contains("cborg"));
}

#[test]
fn test_package_json_typescript_devdep() {
    let g = compile("x = uint");
    assert!(g.package_json.contains("typescript"));
}

#[test]
fn test_package_json_jest() {
    let g = compile("x = uint");
    assert!(g.package_json.contains("jest"));
    assert!(g.package_json.contains("ts-jest"));
}

#[test]
fn test_package_json_build_script() {
    let g = compile("x = uint");
    assert!(g.package_json.contains("\"build\""));
    assert!(g.package_json.contains("tsc"));
}

// ── tsconfig.json ─────────────────────────────────────────────────────────────

#[test]
fn test_tsconfig_es2022_target() {
    let g = compile("x = uint");
    assert!(g.tsconfig.contains("ES2022"));
}

#[test]
fn test_tsconfig_strict_mode() {
    let g = compile("x = uint");
    assert!(g.tsconfig.contains("\"strict\"") && g.tsconfig.contains("true"));
}

#[test]
fn test_tsconfig_declaration() {
    let g = compile("x = uint");
    assert!(g.tsconfig.contains("\"declaration\"") && g.tsconfig.contains("true"));
}

// ── Source file ───────────────────────────────────────────────────────────────

#[test]
fn test_source_generated_comment() {
    let g = compile("x = uint");
    assert!(g.source.contains("@generated by cddlc"));
}

#[test]
fn test_source_imports_cborg() {
    let g = compile("x = uint");
    assert!(g.source.contains("from 'cborg'"));
}

#[test]
fn test_source_has_validation_error() {
    let g = compile("x = uint");
    assert!(g.source.contains("ValidationError"));
}

#[test]
fn test_source_exports_are_named() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("export interface") || g.source.contains("export type") ||
            g.source.contains("export function") || g.source.contains("export class"));
}

// ── Struct ────────────────────────────────────────────────────────────────────

#[test]
fn test_struct_interface() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.source.contains("export interface Sensor"));
}

#[test]
fn test_struct_uint_is_bigint() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("readonly id: bigint"));
}

#[test]
fn test_struct_int_is_bigint() {
    let g = compile("sensor = { count: int }");
    assert!(g.source.contains("readonly count: bigint"));
}

#[test]
fn test_struct_float_is_number() {
    let g = compile("sensor = { value: float32 }");
    assert!(g.source.contains("readonly value: number"));
}

#[test]
fn test_struct_tstr_is_string() {
    let g = compile("msg = { label: tstr }");
    assert!(g.source.contains("readonly label: string"));
}

#[test]
fn test_struct_optional_field() {
    let g = compile("msg = { id: uint, ? label: tstr }");
    assert!(g.source.contains("readonly label?: string") ||
            g.source.contains("label?:"));
}

#[test]
fn test_struct_encode_function() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("export function encodeSensor"));
    assert!(g.source.contains("Uint8Array"));
}

#[test]
fn test_struct_decode_function() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("export function decodeSensor"));
}

#[test]
fn test_struct_encode_writes_map() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.source.contains("startMap(2)"));
}

#[test]
fn test_struct_encode_writes_key() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("enc.text(\"id\")"));
}

#[test]
fn test_struct_decode_checks_map() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("cborgDecode"));
    assert!(g.source.contains("typeof map"));
}

#[test]
fn test_struct_missing_field_throws() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("Missing field") || g.source.contains("undefined"));
}

// ── Tagged struct ─────────────────────────────────────────────────────────────

#[test]
fn test_tagged_struct_encode_tag() {
    let g = compile("tagged-sensor = #6.100({ id: uint })");
    assert!(g.source.contains("tag(100)") || g.source.contains("100"));
}

#[test]
fn test_tagged_struct_decode_verifies_tag() {
    let g = compile("tagged-sensor = #6.100({ id: uint })");
    assert!(g.source.contains("100") && g.source.contains("tag"));
}

// ── Enum (discriminated union) ────────────────────────────────────────────────

#[test]
fn test_enum_is_discriminated_union() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.source.contains("export type Status ="));
    assert!(g.source.contains("kind:"));
}

#[test]
fn test_enum_variants_have_kind() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.source.contains("\"Ok\"") || g.source.contains("'Ok'"));
    assert!(g.source.contains("\"Warn\"") || g.source.contains("'Warn'"));
}

#[test]
fn test_enum_encode_function() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("export function encodeStatus"));
}

#[test]
fn test_enum_decode_function() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("export function decodeStatus"));
}

#[test]
fn test_enum_encode_uses_switch() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("switch (val.kind)"));
}

#[test]
fn test_enum_decode_string_variants() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("typeof inner === 'string'"));
    assert!(g.source.contains("\"ok\"") || g.source.contains("'ok'"));
}

// ── Array ─────────────────────────────────────────────────────────────────────

#[test]
fn test_array_is_readonly_array() {
    let g = compile("readings = [* float32]");
    assert!(g.source.contains("ReadonlyArray<number>"));
}

#[test]
fn test_array_encode_function() {
    let g = compile("readings = [* uint]");
    assert!(g.source.contains("export function encodeReadings"));
}

#[test]
fn test_array_decode_function() {
    let g = compile("readings = [* uint]");
    assert!(g.source.contains("export function decodeReadings"));
}

// ── Alias ─────────────────────────────────────────────────────────────────────

#[test]
fn test_simple_alias_type() {
    let g = compile("device-id = uint");
    assert!(g.source.contains("export type DeviceId = bigint"));
}

#[test]
fn test_constrained_alias_branded_type() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.source.contains("__brand") || g.source.contains("DeviceId"));
}

#[test]
fn test_constrained_alias_validate_fn() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.source.contains("validateDeviceId") || g.source.contains("validate"));
}

#[test]
fn test_constrained_alias_check() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.source.contains(".length === 16"));
}

#[test]
fn test_range_constraint() {
    let g = compile("temp = int .ge -40 .le 85");
    assert!(g.source.contains("-40n") && g.source.contains("85n"));
}

// ── Tagged alias ──────────────────────────────────────────────────────────────

#[test]
fn test_tagged_alias_encode_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("tag(1)") || g.source.contains("1n"));
}

// ── dCBOR ─────────────────────────────────────────────────────────────────────

#[test]
fn test_dcbor_comment() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { b: uint, a: tstr }", opts);
    assert!(g.source.contains("deterministic") || g.source.contains("dCBOR"));
}

#[test]
fn test_dcbor_sorts_keys() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { b: uint, a: tstr }", opts);
    let a_pos = g.source.find("\"a\"").unwrap_or(usize::MAX);
    let b_pos = g.source.find("\"b\"").unwrap_or(0);
    assert!(a_pos < b_pos, "dCBOR: 'a' should be encoded before 'b'");
}

// ── Test file ─────────────────────────────────────────────────────────────────

#[test]
fn test_roundtrip_generated_comment() {
    let g = compile("x = uint");
    assert!(g.tests.contains("@generated by cddlc"));
}

#[test]
fn test_roundtrip_imports_from_source() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("from '../src/"));
}

#[test]
fn test_roundtrip_struct_describe_block() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.tests.contains("describe('Sensor'"));
}

#[test]
fn test_roundtrip_struct_default_test() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.tests.contains("roundtrip default values"));
    assert!(g.tests.contains("encodeSensor"));
    assert!(g.tests.contains("decodeSensor"));
}

#[test]
fn test_roundtrip_struct_explicit_test() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("roundtrip explicit values"));
}

#[test]
fn test_roundtrip_uses_expect() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("expect("));
    assert!(g.tests.contains("toEqual("));
}

#[test]
fn test_roundtrip_enum_per_variant() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.tests.contains("roundtrip Ok") || g.tests.contains("'Ok'"));
    assert!(g.tests.contains("roundtrip Warn") || g.tests.contains("'Warn'"));
}

#[test]
fn test_roundtrip_alias_valid_and_invalid() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.tests.contains("valid value"));
    assert!(g.tests.contains("rejects invalid value"));
    assert!(g.tests.contains("ValidationError"));
}

#[test]
fn test_roundtrip_array_empty() {
    let g = compile("readings = [* float32]");
    assert!(g.tests.contains("Readings") && g.tests.contains("empty array"));
}

#[test]
fn test_iot_schema() {
    let g = compile(r#"
sensor-message = {
    version:   uint,
    device-id: device-id,
    timestamp: #6.1(uint),
}
device-id = tstr .size 16
"#);
    assert!(g.source.contains("interface SensorMessage") ||
            g.source.contains("SensorMessage"));
    assert!(g.source.contains("DeviceId"));
    assert!(g.source.contains(".length === 16"));
}
