/// Node.js / TypeScript backend for cddlc.
///
/// Emits a complete npm package:
///   <module>-{cbor,json}/
///     package.json          ← ESM, optional cborg runtime, jest+ts-jest
///     tsconfig.json         ← TypeScript 5 strict
///     src/<module>.ts       ← interfaces + encode/decode functions
///     tests/roundtrip.test.ts ← Jest roundtrip tests

use cddlc_codegen::{
    to_pascal_case, to_snake_case,
    Backend, CodegenError, CodegenOptions, CodegenOutput, GeneratedFile,
    IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, Constraint, EnumDef,
    IrModule, LiteralValue, Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct NodeJsBackend;

impl Backend for NodeJsBackend {
    fn language_name(&self) -> &str { "Node.js" }
    fn file_extension(&self) -> &str { "ts" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let name      = module.name.as_str();
        let fmt_tag   = if opts.is_json() { "json" } else { "cbor" };
        let crate_dir = format!("{name}-{fmt_tag}");

        Ok(CodegenOutput {
            files: vec![
                GeneratedFile {
                    path:    format!("{crate_dir}/package.json"),
                    content: emit_package_json(name, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/tsconfig.json"),
                    content: emit_tsconfig(),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/src/{name}.ts"),
                    content: emit_source(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/tests/roundtrip.test.ts"),
                    content: emit_tests(module, opts),
                },
            ],
        })
    }
}

// ── package.json ──────────────────────────────────────────────────────────────

fn emit_package_json(name: &str, opts: &CodegenOptions) -> String {
    let fmt_tag = if opts.is_json() { "json" } else { "cbor" };
    let deps = if opts.is_json() {
        // JSON and Buffer are Node.js builtins — no extra runtime needed
        r#"  "dependencies": {}"#.to_owned()
    } else {
        format!(r#"  "dependencies": {{
    "cborg": "^4.0.0"
  }}"#)
    };
    format!(r#"{{
  "name": "{name}-{fmt_tag}",
  "version": "0.1.0",
  "description": "@generated by cddlc",
  "type": "module",
  "main": "./dist/src/{name}.js",
  "types": "./dist/src/{name}.d.ts",
  "scripts": {{
    "build": "tsc",
    "test":  "jest"
  }},
{deps},
  "devDependencies": {{
    "@types/jest":    "^29.0.0",
    "jest":           "^29.0.0",
    "ts-jest":        "^29.0.0",
    "typescript":     "^5.0.0"
  }},
  "jest": {{
    "preset":        "ts-jest/presets/default-esm",
    "testEnvironment": "node",
    "extensionsToTreatAsEsm": [".ts"],
    "moduleNameMapper": {{
      "^(\\.{{1,2}}/.+)\\.js$": "$1"
    }},
    "transform": {{
      "^.+\\.tsx?$": ["ts-jest", {{ "useESM": true }}]
    }}
  }}
}}
"#)
}

// ── tsconfig.json ─────────────────────────────────────────────────────────────

fn emit_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target":           "ES2022",
    "module":           "ES2022",
    "moduleResolution": "bundler",
    "lib":              ["ES2022"],
    "outDir":           "./dist",
    "rootDir":          ".",
    "strict":           true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "declaration":      true,
    "declarationMap":   true,
    "sourceMap":        true,
    "esModuleInterop":  false,
    "skipLibCheck":     true
  },
  "include": ["src/**/*", "tests/**/*"],
  "exclude": ["node_modules", "dist"]
}
"#.to_owned()
}

// ── Source file ───────────────────────────────────────────────────────────────

fn emit_source(module: &IrModule, opts: &CodegenOptions) -> String {
    let mut w = IndentWriter::new(2);

    w.line("// @generated by cddlc — do not edit manually");
    let fmt_label = if opts.is_json() { "JSON (RFC 8259)" } else { "CBOR (RFC 8949)" };
    w.line(&format!("// Format: {fmt_label}"));
    if opts.dcbor { w.line("// Encoding: deterministic (dCBOR)"); }
    w.blank();
    if opts.is_json() {
        // JSON is a Node.js/browser built-in — no imports needed
        // Buffer for base64url encoding (Node.js built-in)
    } else {
        w.line("import { encode as cborgEncode, decode as cborgDecode, Encoder } from 'cborg';");
    }
    w.blank();

    // Validation error class
    w.line("/** Thrown when a decoded value fails a CDDL constraint. */");
    w.line("export class ValidationError extends Error {");
    w.indent();
    w.line("constructor(");
    w.indent();
    w.line("public readonly field: string,");
    w.line("message: string,");
    w.dedent();
    w.line(") {");
    w.indent();
    w.line("super(`Validation failed for '${field}': ${message}`);");
    w.line("this.name = 'ValidationError';");
    w.dedent();
    w.line("}");
    w.dedent();
    w.line("}");

    // JSON base64url helpers
    if opts.is_json() {
        w.blank();
        w.line("function toBase64Url(bytes: Uint8Array): string {");
        w.indent();
        w.line("return Buffer.from(bytes).toString('base64url');");
        w.dedent();
        w.line("}");
        w.blank();
        w.line("function fromBase64Url(s: string): Uint8Array {");
        w.indent();
        w.line("return new Uint8Array(Buffer.from(s, 'base64url'));");
        w.dedent();
        w.line("}");
    }

    w.blank();

    // Emit each type
    for (_, def) in &module.types {
        emit_type(&mut w, def, opts);
        w.blank();
    }

    w.finish()
}

fn emit_type(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct(w, s, opts),
        TypeDef::Enum(e)   => emit_enum(w, e, opts),
        TypeDef::Array(a)  => emit_array(w, a, opts),
        TypeDef::Alias(a)  => emit_alias(w, a, opts),
        TypeDef::Map(_)    => {}
    }
}

// ── Interface + encode/decode ─────────────────────────────────────────────────

fn emit_struct(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    let iname = to_pascal_case(&s.name);
    let fname = encode_fn_name(&s.name);
    let dname = decode_fn_name(&s.name);

    if let Some(doc) = s.doc.as_deref() { w.line(&format!("/** {} */", doc)); }
    if s.deprecated { w.line("/** @deprecated */"); }

    // Interface
    w.line(&format!("export interface {iname} {{"));
    w.indent();
    for f in &s.fields {
        if let Some(doc) = f.doc.as_deref() { w.line(&format!("/** {} */", doc)); }
        let opt  = if matches!(f.occurrence, Occurrence::Optional) { "?" } else { "" };
        let ty   = ts_field_type(&f.ty, &f.occurrence, opts);
        let prop = to_snake_case(&f.name);
        w.line(&format!("readonly {prop}{opt}: {ty};"));
    }
    w.dedent();
    w.line("}");
    w.blank();

    if opts.is_json() {
        emit_struct_encode_json(w, s, &iname, &fname, opts);
        w.blank();
        emit_struct_decode_json(w, s, &iname, &dname, opts);
    } else {
        emit_struct_encode_cbor(w, s, &iname, &fname, opts);
        w.blank();
        emit_struct_decode_cbor(w, s, &iname, &dname, opts);
    }
}

fn emit_struct_encode_json(
    w: &mut IndentWriter,
    s: &StructDef,
    iname: &str,
    fname: &str,
    opts: &CodegenOptions,
) {
    let fields: Vec<_> = if opts.dcbor {
        let mut fs: Vec<_> = s.fields.iter().collect();
        fs.sort_by(|a, b| a.name.cmp(&b.name));
        fs
    } else {
        s.fields.iter().collect()
    };

    w.line(&format!("export function {fname}(val: {iname}): Uint8Array {{"));
    w.indent();
    w.line("const _map: Record<string, unknown> = {};");
    for f in &fields {
        let prop = to_snake_case(&f.name);
        let key  = f.name.as_str();
        let expr = ts_json_encode_expr(&f.ty, &format!("val.{prop}"), opts);
        match &f.occurrence {
            Occurrence::Optional => {
                w.line(&format!("if (val.{prop} !== undefined) _map[{key:?}] = {expr};"));
            }
            _ => {
                w.line(&format!("_map[{key:?}] = {expr};"));
            }
        }
    }
    w.line("return new TextEncoder().encode(JSON.stringify(_map));");
    w.dedent();
    w.line("}");
}

fn emit_struct_encode_cbor(
    w: &mut IndentWriter,
    s: &StructDef,
    iname: &str,
    fname: &str,
    opts: &CodegenOptions,
) {
    let fields: Vec<_> = if opts.dcbor {
        let mut fs: Vec<_> = s.fields.iter().collect();
        fs.sort_by(|a, b| a.name.cmp(&b.name));
        fs
    } else {
        s.fields.iter().collect()
    };

    w.line(&format!("export function {fname}(val: {iname}): Uint8Array {{"));
    w.indent();
    w.line("const enc = new Encoder({ typeEncoders: {} });");

    if let Some(tag) = s.tagged {
        w.line(&format!("enc.tag({});", tag.0));
    }

    w.line(&format!("enc.startMap({});", fields.len()));
    for f in &fields {
        let prop = to_snake_case(&f.name);
        w.line(&format!("enc.text({:?});", f.name.as_str()));
        emit_ts_encode_value(w, &f.ty, &format!("val.{prop}"), &f.occurrence, opts);
    }
    w.line("enc.endMap();");
    w.line("return enc.finish();");
    w.dedent();
    w.line("}");
}

fn emit_struct_decode_json(
    w: &mut IndentWriter,
    s: &StructDef,
    iname: &str,
    dname: &str,
    opts: &CodegenOptions,
) {
    w.line(&format!("export function {dname}(data: Uint8Array): {iname} {{"));
    w.indent();
    w.line("const raw: unknown = JSON.parse(new TextDecoder().decode(data));");
    w.line("if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {");
    w.indent();
    w.line("throw new Error('Expected JSON object');");
    w.dedent();
    w.line("}");
    w.line("const m = raw as Record<string, unknown>;");
    w.blank();

    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        let key  = f.name.as_str();
        let ty   = ts_field_type(&f.ty, &f.occurrence, opts);
        match &f.occurrence {
            Occurrence::Optional => {
                w.line(&format!("const {prop}: {ty} = m[{key:?}] !== undefined"));
                w.indent();
                let conv = ts_json_decode_expr(&f.ty, &format!("m[{key:?}]"), opts);
                w.line(&format!("? {conv}"));
                w.line(": undefined;");
                w.dedent();
            }
            _ => {
                w.line(&format!("if (m[{key:?}] === undefined) throw new Error('Missing field {key}');"));
                let conv = ts_json_decode_expr(&f.ty, &format!("m[{key:?}]"), opts);
                w.line(&format!("const {prop}: {ty} = {conv};"));
                emit_ts_validation(w, &f.constraints, &prop, key);
            }
        }
    }
    w.blank();

    w.line("return {");
    w.indent();
    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        w.line(&format!("{prop},"));
    }
    w.dedent();
    w.line("};");
    w.dedent();
    w.line("}");
}

fn emit_struct_decode_cbor(
    w: &mut IndentWriter,
    s: &StructDef,
    iname: &str,
    dname: &str,
    opts: &CodegenOptions,
) {
    w.line(&format!("export function {dname}(data: Uint8Array): {iname} {{"));
    w.indent();

    if let Some(tag) = s.tagged {
        w.line("const decoded = cborgDecode(data);");
        w.line("if (!Array.isArray(decoded) || decoded.length < 2) throw new Error('Expected CBOR tag');");
        w.line(&format!("if (decoded[0] !== {}n) throw new Error('Unexpected CBOR tag');", tag.0));
        w.line("const map: unknown = decoded[1];");
    } else {
        w.line("const map: unknown = cborgDecode(data);");
    }

    w.line("if (typeof map !== 'object' || map === null || Array.isArray(map)) {");
    w.indent();
    w.line("throw new Error('Expected CBOR map');");
    w.dedent();
    w.line("}");
    w.line("const m = map as Record<string, unknown>;");
    w.blank();

    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        let key  = f.name.as_str();
        let ty   = ts_field_type(&f.ty, &f.occurrence, opts);
        match &f.occurrence {
            Occurrence::Optional => {
                w.line(&format!("const {prop}: {ty} = m[{:?}] !== undefined", key));
                w.indent();
                let conv = ts_convert_expr(&f.ty, &format!("m[{:?}]", key), opts);
                w.line(&format!("? {conv}"));
                w.line(": undefined;");
                w.dedent();
            }
            _ => {
                w.line(&format!("if (m[{:?}] === undefined) throw new Error('Missing field {key}');", key));
                let conv = ts_convert_expr(&f.ty, &format!("m[{:?}]", key), opts);
                w.line(&format!("const {prop}: {ty} = {conv};"));
                emit_ts_validation(w, &f.constraints, &prop, key);
            }
        }
    }
    w.blank();

    w.line("return {");
    w.indent();
    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        w.line(&format!("{prop},"));
    }
    w.dedent();
    w.line("};");
    w.dedent();
    w.line("}");
}

// ── Enum (discriminated union) ────────────────────────────────────────────────

fn emit_enum(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&e.name);
    let fname     = encode_fn_name(&e.name);
    let dname     = decode_fn_name(&e.name);

    if let Some(doc) = e.doc.as_deref() { w.line(&format!("/** {} */", doc)); }
    if e.deprecated { w.line("/** @deprecated */"); }

    // Discriminated union type
    w.line(&format!("export type {type_name} ="));
    w.indent();
    for (i, v) in e.variants.iter().enumerate() {
        let vname = to_pascal_case(&v.name);
        let sep   = if i < e.variants.len() - 1 { " |" } else { ";" };
        match &v.ty {
            TypeRef::Primitive(Primitive::Tstr | Primitive::Null) => {
                w.line(&format!("{{ readonly kind: {:?} }}{sep}", vname));
            }
            TypeRef::Primitive(p) => {
                let ts = ts_primitive(p, opts);
                w.line(&format!("{{ readonly kind: {:?}; readonly value: {ts} }}{sep}", vname));
            }
            TypeRef::Named(n) => {
                let ct = to_pascal_case(n);
                w.line(&format!("{{ readonly kind: {:?}; readonly value: {ct} }}{sep}", vname));
            }
            _ => {
                w.line(&format!("{{ readonly kind: {:?} }}{sep}", vname));
            }
        }
    }
    w.dedent();
    w.blank();

    // Encode function
    w.line(&format!("export function {fname}(val: {type_name}): Uint8Array {{"));
    w.indent();
    if opts.is_json() {
        w.line("switch (val.kind) {");
        w.indent();
        for v in &e.variants {
            let vname    = to_pascal_case(&v.name);
            let cddl_str = v.name.to_lowercase().replace('_', "-");
            w.line(&format!("case {:?}:", vname));
            w.indent();
            match &v.ty {
                TypeRef::Primitive(Primitive::Tstr | Primitive::Null) => {
                    w.line(&format!("return new TextEncoder().encode(JSON.stringify({cddl_str:?}));"));
                }
                TypeRef::Named(_) => {
                    w.line("if (!('value' in val)) throw new Error('Missing value');");
                    let ef = encode_fn_name(v.name.as_str());
                    w.line(&format!("return {ef}((val as any).value); break;"));
                }
                _ => {
                    w.line("if (!('value' in val)) throw new Error('Missing value');");
                    w.line("return new TextEncoder().encode(JSON.stringify((val as any).value));");
                }
            }
            w.dedent();
        }
        w.dedent();
        w.line("}");
        w.line("throw new Error(`Unknown kind: ${(val as any).kind}`);");
    } else {
        w.line("const enc = new Encoder({ typeEncoders: {} });");
        if let Some(tag) = e.tagged { w.line(&format!("enc.tag({});", tag.0)); }
        w.line("switch (val.kind) {");
        w.indent();
        for v in &e.variants {
            let vname = to_pascal_case(&v.name);
            w.line(&format!("case {:?}:", vname));
            w.indent();
            match &v.ty {
                TypeRef::Primitive(Primitive::Tstr | Primitive::Null) => {
                    let s = v.name.to_lowercase().replace('_', "-");
                    w.line(&format!("enc.text({s:?}); break;"));
                }
                TypeRef::Primitive(Primitive::Uint) =>
                    w.line("enc.uint((val as any).value); break;"),
                TypeRef::Primitive(Primitive::Int) =>
                    w.line("enc.int((val as any).value); break;"),
                TypeRef::Primitive(Primitive::Bool) =>
                    w.line("enc.bool((val as any).value); break;"),
                TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) =>
                    w.line("enc.float32((val as any).value); break;"),
                TypeRef::Primitive(Primitive::Float64 | Primitive::Float) =>
                    w.line("enc.float64((val as any).value); break;"),
                TypeRef::Named(n) => {
                    let ef = encode_fn_name(n);
                    w.line(&format!("enc.writeBytes({ef}((val as any).value)); break;"));
                }
                _ => w.line("enc.null(); break;"),
            }
            w.dedent();
        }
        w.dedent();
        w.line("}");
        w.line("return enc.finish();");
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Decode function
    w.line(&format!("export function {dname}(data: Uint8Array): {type_name} {{"));
    w.indent();
    if opts.is_json() {
        w.line("const inner: unknown = JSON.parse(new TextDecoder().decode(data));");
    } else {
        w.line("const val: unknown = cborgDecode(data);");
        if let Some(tag) = e.tagged {
            w.line("if (!Array.isArray(val)) throw new Error('Expected CBOR tag');");
            w.line(&format!("if (val[0] !== {}n) throw new Error('Unexpected CBOR tag');", tag.0));
            w.line("const inner: unknown = val[1];");
        } else {
            w.line("const inner: unknown = val;");
        }
    }

    let has_str = e.variants.iter().any(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr | Primitive::Null)));
    let has_int = e.variants.iter().any(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)));

    if has_str {
        w.line("if (typeof inner === 'string') {");
        w.indent();
        w.line("switch (inner) {");
        w.indent();
        for v in &e.variants {
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Tstr | Primitive::Null)) {
                let vname    = to_pascal_case(&v.name);
                let cddl_str = v.name.to_lowercase().replace('_', "-");
                w.line(&format!("case {cddl_str:?}: return {{ kind: {vname:?} }};"));
            }
        }
        w.line(&format!("default: throw new Error(`Unknown {type_name} variant: ${{inner}}`);"));
        w.dedent();
        w.line("}");
        w.dedent();
        w.line("}");
    }

    if has_int {
        let num_check = if opts.is_json() { "typeof inner === 'number'" } else { "typeof inner === 'bigint'" };
        w.line(&format!("if ({num_check}) {{"));
        w.indent();
        for v in &e.variants {
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)) {
                let vname = to_pascal_case(&v.name);
                w.line(&format!("return {{ kind: {vname:?}, value: inner }};"));
                break;
            }
        }
        w.dedent();
        w.line("}");
    }

    w.line(&format!("throw new Error(`Cannot decode {type_name}`);"));
    w.dedent();
    w.line("}");
}

// ── Array ─────────────────────────────────────────────────────────────────────

fn emit_array(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&a.name);
    let elem_ty   = ts_typeref(&a.element, opts);
    let fname     = encode_fn_name(&a.name);
    let dname     = decode_fn_name(&a.name);

    if let Some(doc) = a.doc.as_deref() { w.line(&format!("/** {} */", doc)); }
    if a.deprecated { w.line("/** @deprecated */"); }

    w.line(&format!("export type {type_name} = ReadonlyArray<{elem_ty}>;"));
    w.blank();

    // Encode
    w.line(&format!("export function {fname}(val: {type_name}): Uint8Array {{"));
    w.indent();
    if opts.is_json() {
        let conv = ts_json_encode_expr(&a.element, "item", opts);
        if conv == "item" {
            w.line("return new TextEncoder().encode(JSON.stringify(val));");
        } else {
            w.line(&format!("return new TextEncoder().encode(JSON.stringify((val as unknown[]).map(item => {conv})));"));
        }
    } else if let Some(tag) = a.tagged {
        w.line(&format!("return cborgEncode([{}n, val]);", tag.0));
    } else {
        w.line("return cborgEncode(val);");
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Decode
    w.line(&format!("export function {dname}(data: Uint8Array): {type_name} {{"));
    w.indent();
    if opts.is_json() {
        w.line("const arr: unknown = JSON.parse(new TextDecoder().decode(data));");
        w.line("if (!Array.isArray(arr)) throw new Error('Expected JSON array');");
        let conv = ts_json_decode_expr(&a.element, "item", opts);
        w.line(&format!("return (arr as unknown[]).map(item => {conv}) as {type_name};"));
    } else {
        if let Some(_tag) = a.tagged {
            w.line("const decoded = cborgDecode(data);");
            w.line("if (!Array.isArray(decoded) || decoded[0] !== {}n) throw new Error('Unexpected tag');", );
            w.line("const arr: unknown = decoded[1];");
        } else {
            w.line("const arr: unknown = cborgDecode(data);");
        }
        w.line("if (!Array.isArray(arr)) throw new Error('Expected CBOR array');");
        let conv = ts_convert_expr(&a.element, "item", opts);
        w.line(&format!("return (arr as unknown[]).map(item => {conv}) as {type_name};"));
    }
    w.dedent();
    w.line("}");
}

// ── Alias ─────────────────────────────────────────────────────────────────────

fn emit_alias(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&a.name);
    let fname     = encode_fn_name(&a.name);
    let dname     = decode_fn_name(&a.name);
    let inner_ty  = ts_typeref(&a.ty, opts);

    if let Some(doc) = a.doc.as_deref() { w.line(&format!("/** {} */", doc)); }
    if a.deprecated { w.line("/** @deprecated */"); }

    // Type alias
    if a.constraints.is_empty() && a.tagged.is_none() {
        w.line(&format!("export type {type_name} = {inner_ty};"));
        w.blank();
        w.line(&format!("export function {fname}(val: {type_name}): Uint8Array {{"));
        w.indent();
        if opts.is_json() {
            let expr = ts_json_encode_expr(&a.ty, "val", opts);
            w.line(&format!("return new TextEncoder().encode(JSON.stringify({expr}));"));
        } else {
            emit_ts_encode_value(w, &a.ty, "val", &Occurrence::Required, opts);
            w.line("return enc.finish();");
        }
        w.dedent();
        w.line("}");
        w.blank();
        w.line(&format!("export function {dname}(data: Uint8Array): {type_name} {{"));
        w.indent();
        if opts.is_json() {
            w.line("const raw: unknown = JSON.parse(new TextDecoder().decode(data));");
            let conv = ts_json_decode_expr(&a.ty, "raw", opts);
            w.line(&format!("return {conv};"));
        } else {
            w.line("const raw: unknown = cborgDecode(data);");
            let conv = ts_convert_expr(&a.ty, "raw", opts);
            w.line(&format!("return {conv};"));
        }
        w.dedent();
        w.line("}");
        return;
    }

    // Branded type for constrained/tagged aliases
    w.line(&format!("export type {type_name} = {inner_ty} & {{ readonly __brand: '{type_name}' }};"));
    w.blank();

    // Validate function
    w.line(&format!("export function validate{type_name}(val: {inner_ty}): {type_name} {{"));
    w.indent();
    for c in &a.constraints {
        if let Some(check) = ts_constraint_check(c, "val") {
            let msg = ts_constraint_description(c);
            w.line(&format!("if (!({check})) throw new ValidationError({type_name:?}, {msg:?});"));
        }
    }
    w.line(&format!("return val as {type_name};"));
    w.dedent();
    w.line("}");
    w.blank();

    // Encode
    w.line(&format!("export function {fname}(val: {type_name}): Uint8Array {{"));
    w.indent();
    if opts.is_json() {
        let expr = ts_json_encode_expr(&a.ty, "val", opts);
        w.line(&format!("return new TextEncoder().encode(JSON.stringify({expr}));"));
    } else {
        w.line("const enc = new Encoder({ typeEncoders: {} });");
        if let Some(tag) = a.tagged { w.line(&format!("enc.tag({});", tag.0)); }
        emit_ts_encode_primitive_or_named(w, &a.ty, "val", opts);
        w.line("return enc.finish();");
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Decode with validation
    w.line(&format!("export function {dname}(data: Uint8Array): {type_name} {{"));
    w.indent();
    if opts.is_json() {
        w.line("const raw: unknown = JSON.parse(new TextDecoder().decode(data));");
        let conv = ts_json_decode_expr(&a.ty, "raw", opts);
        w.line(&format!("const val = {conv};"));
    } else if let Some(tag) = a.tagged {
        w.line("const decoded = cborgDecode(data);");
        w.line("if (!Array.isArray(decoded)) throw new Error('Expected CBOR tag');");
        w.line(&format!("if (decoded[0] !== {}n) throw new Error('Unexpected CBOR tag');", tag.0));
        w.line("const raw: unknown = decoded[1];");
        let conv = ts_convert_expr(&a.ty, "raw", opts);
        w.line(&format!("const val = {conv};"));
    } else {
        w.line("const raw: unknown = cborgDecode(data);");
        let conv = ts_convert_expr(&a.ty, "raw", opts);
        w.line(&format!("const val = {conv};"));
    }
    w.line(&format!("return validate{type_name}(val);"));
    w.dedent();
    w.line("}");
}

// ── JSON encode/decode expression helpers ─────────────────────────────────────

/// Produce an expression that converts a TS value to its JSON-serializable form.
fn ts_json_encode_expr(ty: &TypeRef, expr: &str, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(Primitive::Bstr | Primitive::Any) =>
            format!("toBase64Url({expr})"),
        TypeRef::Named(n) => {
            let ef = encode_fn_name(n);
            // encode returns Uint8Array; convert to JSON string and parse back
            format!("JSON.parse(new TextDecoder().decode({ef}({expr})))")
        }
        TypeRef::Tagged(_, inner) => ts_json_encode_expr(inner, expr, opts),
        _ => expr.to_owned(),
    }
}

/// Produce an expression that converts a JSON-decoded `unknown` value to the correct TS type.
fn ts_json_decode_expr(ty: &TypeRef, raw_expr: &str, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p) => ts_json_convert_primitive(p, raw_expr),
        TypeRef::Named(n) => {
            let df = decode_fn_name(n);
            format!("{df}(new TextEncoder().encode(JSON.stringify({raw_expr})))")
        }
        TypeRef::Tagged(_, inner) => ts_json_decode_expr(inner, raw_expr, opts),
        TypeRef::Choice(_) => format!("{raw_expr} as unknown"),
    }
}

fn ts_json_convert_primitive(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Uint | Primitive::Int =>
            format!("Number({expr}) as number"),
        Primitive::Bool =>
            format!("Boolean({expr})"),
        Primitive::Float16 | Primitive::Float32 | Primitive::Float64 | Primitive::Float =>
            format!("Number({expr}) as number"),
        Primitive::Tstr =>
            format!("String({expr})"),
        Primitive::Bstr | Primitive::Any =>
            format!("fromBase64Url(String({expr}))"),
        Primitive::Null | Primitive::Undefined =>
            "null".into(),
    }
}

// ── CBOR encode helpers ────────────────────────────────────────────────────────

fn emit_ts_encode_value(
    w:    &mut IndentWriter,
    ty:   &TypeRef,
    expr: &str,
    occ:  &Occurrence,
    opts: &CodegenOptions,
) {
    match occ {
        Occurrence::Optional => {
            w.line(&format!("if ({expr} !== undefined) {{"));
            w.indent();
            emit_ts_encode_primitive_or_named(w, ty, expr, opts);
            w.dedent();
            w.line("} else { enc.null(); }");
        }
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => {
            w.line(&format!("enc.startArray({expr}.length);"));
            w.line(&format!("for (const item of {expr}) {{"));
            w.indent();
            emit_ts_encode_primitive_or_named(w, ty, "item", opts);
            w.dedent();
            w.line("}");
            w.line("enc.endArray();");
        }
        Occurrence::Required => {
            emit_ts_encode_primitive_or_named(w, ty, expr, opts);
        }
    }
}

fn emit_ts_encode_primitive_or_named(
    w:    &mut IndentWriter,
    ty:   &TypeRef,
    expr: &str,
    opts: &CodegenOptions,
) {
    match ty {
        TypeRef::Primitive(p) => {
            let call = ts_encode_call(p, expr);
            w.line(&format!("{call};"));
        }
        TypeRef::Named(n) => {
            let ef = encode_fn_name(n);
            w.line(&format!("enc.writeBytes({ef}({expr}));"));
        }
        TypeRef::Tagged(tag, inner) => {
            w.line(&format!("enc.tag({});", tag.0));
            emit_ts_encode_primitive_or_named(w, inner, expr, opts);
        }
        TypeRef::Choice(_) => {
            w.line(&format!("enc.writeBytes(cborgEncode({expr}));"));
        }
    }
}

fn ts_encode_call(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Bool      => format!("enc.bool({expr})"),
        Primitive::Null | Primitive::Undefined => "enc.null()".into(),
        Primitive::Uint      => format!("enc.uint({expr})"),
        Primitive::Int       => format!("enc.int({expr})"),
        Primitive::Float16   => format!("enc.float32(Number({expr}))"),
        Primitive::Float32   => format!("enc.float32({expr})"),
        Primitive::Float64 | Primitive::Float => format!("enc.float64({expr})"),
        Primitive::Tstr      => format!("enc.text({expr})"),
        Primitive::Bstr | Primitive::Any => format!("enc.bytes({expr})"),
    }
}

// ── CBOR Convert/decode helpers ───────────────────────────────────────────────

fn emit_ts_validation(
    w:           &mut IndentWriter,
    constraints: &[Constraint],
    expr:        &str,
    field_name:  &str,
) {
    for c in constraints {
        if let Some(check) = ts_constraint_check(c, expr) {
            let msg = ts_constraint_description(c);
            w.line(&format!("if (!({check})) throw new ValidationError({field_name:?}, {msg:?});"));
        }
    }
}

fn ts_convert_expr(ty: &TypeRef, raw_expr: &str, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p) => ts_convert_primitive(p, raw_expr),
        TypeRef::Named(n) => {
            let df = decode_fn_name(n);
            format!("{df}(cborgEncode({raw_expr}))")
        }
        TypeRef::Tagged(_, inner) => ts_convert_expr(inner, raw_expr, opts),
        TypeRef::Choice(_) => format!("{raw_expr} as unknown"),
    }
}

fn ts_convert_primitive(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Uint | Primitive::Int =>
            format!("BigInt({expr} as string | number | bigint)"),
        Primitive::Bool =>
            format!("Boolean({expr})"),
        Primitive::Float16 | Primitive::Float32 =>
            format!("Number({expr}) as number"),
        Primitive::Float64 | Primitive::Float =>
            format!("Number({expr}) as number"),
        Primitive::Tstr =>
            format!("String({expr})"),
        Primitive::Bstr | Primitive::Any =>
            format!("{expr} as Uint8Array"),
        Primitive::Null | Primitive::Undefined =>
            "null".into(),
    }
}

// ── Constraint helpers ────────────────────────────────────────────────────────

fn ts_constraint_check(c: &Constraint, expr: &str) -> Option<String> {
    match c {
        Constraint::SizeExact(n) =>
            Some(format!("{expr}.length === {n}")),
        Constraint::SizeRange { min, max } => match (min, max) {
            (Some(lo), Some(hi)) => Some(format!("{expr}.length >= {lo} && {expr}.length <= {hi}")),
            (Some(lo), None)     => Some(format!("{expr}.length >= {lo}")),
            (None, Some(hi))     => Some(format!("{expr}.length <= {hi}")),
            (None, None)         => None,
        },
        Constraint::ValueRangeInt { min, max, inclusive } => {
            let op = if *inclusive { "=" } else { "" };
            match (min, max) {
                (Some(lo), Some(hi)) => Some(format!("{expr} >={op} {}n && {expr} <={op} {}n", lo, hi)),
                (Some(lo), None)     => Some(format!("{expr} >={op} {}n", lo)),
                (None, Some(hi))     => Some(format!("{expr} <={op} {}n", hi)),
                (None, None)         => None,
            }
        }
        Constraint::ValueRangeUint { min, max, inclusive } => {
            let op = if *inclusive { "=" } else { "" };
            match (min, max) {
                (Some(lo), Some(hi)) => Some(format!("{expr} >={op} {}n && {expr} <={op} {}n", lo, hi)),
                (Some(lo), None)     => Some(format!("{expr} >={op} {}n", lo)),
                (None, Some(hi))     => Some(format!("{expr} <={op} {}n", hi)),
                (None, None)         => None,
            }
        }
        Constraint::Eq(v)  => Some(format!("{expr} === {}", ts_literal(v))),
        Constraint::Ne(v)  => Some(format!("{expr} !== {}", ts_literal(v))),
        Constraint::Regexp { hook: Some(h), .. } => Some(format!("{h}({expr})")),
        _ => None,
    }
}

fn ts_constraint_description(c: &Constraint) -> String {
    match c {
        Constraint::SizeExact(n)    => format!("length must be {n}"),
        Constraint::SizeRange { min, max } => format!("length out of range ({min:?}..{max:?})"),
        Constraint::ValueRangeInt { min, max, .. } => format!("value out of range ({min:?}..{max:?})"),
        Constraint::ValueRangeUint { min, max, .. } => format!("value out of range ({min:?}..{max:?})"),
        Constraint::Eq(v)  => format!("must equal {}", ts_literal(v)),
        Constraint::Ne(v)  => format!("must not equal {}", ts_literal(v)),
        _                  => "constraint violated".into(),
    }
}

fn ts_literal(v: &LiteralValue) -> String {
    match v {
        LiteralValue::Bool(b)  => b.to_string(),
        LiteralValue::Null     => "null".into(),
        LiteralValue::Uint(n)  => format!("{n}n"),
        LiteralValue::Int(n)   => format!("{n}n"),
        LiteralValue::Float(f) => format!("{f}"),
        LiteralValue::Text(s)  => format!("{s:?}"),
        LiteralValue::Bytes(_) => "new Uint8Array()".into(),
    }
}

// ── TypeScript type helpers ───────────────────────────────────────────────────

fn ts_field_type(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    let base = ts_typeref(ty, opts);
    match occ {
        Occurrence::Optional => base,   // field marked with `?` in interface
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => format!("ReadonlyArray<{base}>"),
        Occurrence::Required => base,
    }
}

fn ts_typeref(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)     => ts_primitive(p, opts).to_owned(),
        TypeRef::Named(n)         => to_pascal_case(n),
        TypeRef::Tagged(_, inner) => ts_typeref(inner, opts),
        TypeRef::Choice(cs)       => {
            if cs.is_empty() { return "unknown".into(); }
            cs.iter().map(|c| ts_typeref(c, opts))
              .collect::<Vec<_>>().join(" | ")
        }
    }
}

fn ts_primitive(p: &Primitive, opts: &CodegenOptions) -> &'static str {
    match p {
        Primitive::Bool      => "boolean",
        Primitive::Null | Primitive::Undefined => "null",
        Primitive::Uint | Primitive::Int => if opts.is_json() { "number" } else { "bigint" },
        Primitive::Float16 | Primitive::Float32 => "number",
        Primitive::Float64 | Primitive::Float   => "number",
        Primitive::Tstr      => "string",
        Primitive::Bstr | Primitive::Any => "Uint8Array",
    }
}

// ── Name helpers ──────────────────────────────────────────────────────────────

fn encode_fn_name(name: &str) -> String {
    format!("encode{}", to_pascal_case(name))
}

fn decode_fn_name(name: &str) -> String {
    format!("decode{}", to_pascal_case(name))
}

// ── Test file ─────────────────────────────────────────────────────────────────

fn emit_tests(module: &IrModule, opts: &CodegenOptions) -> String {
    let name  = module.name.as_str();
    let mut w = IndentWriter::new(2);

    w.line("// @generated by cddlc — do not edit manually");
    w.blank();

    // Build import list
    let mut imports: Vec<String> = vec!["ValidationError".into()];
    for (_, def) in &module.types {
        let n = def.name();
        imports.push(to_pascal_case(n));
        imports.push(encode_fn_name(n));
        imports.push(decode_fn_name(n));
        if matches!(def, TypeDef::Alias(a) if !a.constraints.is_empty()) {
            imports.push(format!("validate{}", to_pascal_case(n)));
        }
    }
    imports.dedup();
    w.line(&format!("import {{ {} }} from '../src/{name}.js';", imports.join(", ")));
    w.blank();

    for (_, def) in &module.types {
        emit_type_tests(&mut w, def, opts);
        w.blank();
    }

    w.finish()
}

fn emit_type_tests(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct_tests(w, s, opts),
        TypeDef::Enum(e)   => emit_enum_tests(w, e, opts),
        TypeDef::Alias(a)  => emit_alias_tests(w, a, opts),
        TypeDef::Array(a)  => emit_array_tests(w, a, opts),
        TypeDef::Map(_)    => {}
    }
}

fn emit_struct_tests(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&s.name);
    let fname     = encode_fn_name(&s.name);
    let dname     = decode_fn_name(&s.name);

    w.line(&format!("describe('{type_name}', () => {{"));
    w.indent();

    w.line("test('roundtrip default values', () => {");
    w.indent();
    w.line(&format!("const original: {type_name} = {{"));
    w.indent();
    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        let val  = ts_default_value(&f.ty, &f.occurrence, opts);
        w.line(&format!("{prop}: {val},"));
    }
    w.dedent();
    w.line("};");
    w.line(&format!("const encoded = {fname}(original);"));
    w.line(&format!("const decoded = {dname}(encoded);"));
    emit_ts_roundtrip_assert(w, s);
    w.dedent();
    w.line("});");
    w.blank();

    w.line("test('roundtrip explicit values', () => {");
    w.indent();
    w.line(&format!("const original: {type_name} = {{"));
    w.indent();
    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        let val  = ts_explicit_value(&f.ty, &f.occurrence, opts);
        w.line(&format!("{prop}: {val},"));
    }
    w.dedent();
    w.line("};");
    w.line(&format!("const encoded = {fname}(original);"));
    w.line(&format!("const decoded = {dname}(encoded);"));
    emit_ts_roundtrip_assert(w, s);
    w.dedent();
    w.line("});");

    if let Some(tag) = s.tagged {
        w.blank();
        w.line(&format!("test('encode contains tag {}', () => {{", tag.0));
        w.indent();
        w.line(&format!("const val: {type_name} = {{"));
        w.indent();
        for f in &s.fields {
            let prop = to_snake_case(&f.name);
            let v    = ts_default_value(&f.ty, &f.occurrence, opts);
            w.line(&format!("{prop}: {v},"));
        }
        w.dedent();
        w.line("};");
        w.line(&format!("const encoded = {fname}(val);"));
        w.line("expect(encoded.length).toBeGreaterThan(0);");
        w.dedent();
        w.line("});");
    }

    w.dedent();
    w.line("});");
}

fn emit_ts_roundtrip_assert(w: &mut IndentWriter, s: &StructDef) {
    for f in &s.fields {
        let prop = to_snake_case(&f.name);
        w.line(&format!("expect(decoded.{prop}).toEqual(original.{prop});"));
    }
}

fn emit_enum_tests(w: &mut IndentWriter, e: &EnumDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&e.name);
    let fname     = encode_fn_name(&e.name);
    let dname     = decode_fn_name(&e.name);

    w.line(&format!("describe('{type_name}', () => {{"));
    w.indent();

    for v in &e.variants {
        let vname   = to_pascal_case(&v.name);
        let construct = match &v.ty {
            TypeRef::Primitive(Primitive::Tstr | Primitive::Null) =>
                format!("{{ kind: {vname:?} }} as {type_name}"),
            TypeRef::Primitive(Primitive::Uint) => if opts.is_json() {
                format!("{{ kind: {vname:?}, value: 42 }} as {type_name}")
            } else {
                format!("{{ kind: {vname:?}, value: 42n }} as {type_name}")
            },
            TypeRef::Primitive(Primitive::Int) => if opts.is_json() {
                format!("{{ kind: {vname:?}, value: -1 }} as {type_name}")
            } else {
                format!("{{ kind: {vname:?}, value: -1n }} as {type_name}")
            },
            TypeRef::Primitive(Primitive::Bool) =>
                format!("{{ kind: {vname:?}, value: false }} as {type_name}"),
            _ => format!("{{ kind: {vname:?} }} as {type_name}"),
        };

        w.line(&format!("test('roundtrip {vname}', () => {{"));
        w.indent();
        w.line(&format!("const original: {type_name} = {construct};"));
        w.line(&format!("const decoded = {dname}({fname}(original));"));
        w.line("expect(decoded.kind).toEqual(original.kind);");
        w.dedent();
        w.line("});");
    }

    w.dedent();
    w.line("});");
}

fn emit_alias_tests(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&a.name);
    let fname     = encode_fn_name(&a.name);
    let dname     = decode_fn_name(&a.name);

    w.line(&format!("describe('{type_name}', () => {{"));
    w.indent();

    let valid_val = ts_valid_constrained_value(&a.constraints, &a.ty, opts);
    w.line("test('roundtrip valid value', () => {");
    w.indent();
    if a.constraints.is_empty() && a.tagged.is_none() {
        w.line(&format!("const original = {valid_val};"));
        w.line(&format!("const decoded = {dname}({fname}(original));"));
        w.line("expect(decoded).toEqual(original);");
    } else {
        w.line(&format!("const original = validate{type_name}({valid_val});"));
        w.line(&format!("const decoded = {dname}({fname}(original));"));
        w.line("expect(decoded).toEqual(original);");
    }
    w.dedent();
    w.line("});");

    if !a.constraints.is_empty() {
        w.blank();
        let bad_val = ts_invalid_constrained_value(&a.constraints, &a.ty, opts);
        w.line("test('rejects invalid value', () => {");
        w.indent();
        w.line(&format!("expect(() => validate{type_name}({bad_val})).toThrow(ValidationError);"));
        w.dedent();
        w.line("});");
    }

    w.dedent();
    w.line("});");
}

fn emit_array_tests(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    let type_name = to_pascal_case(&a.name);
    let fname     = encode_fn_name(&a.name);
    let dname     = decode_fn_name(&a.name);

    w.line(&format!("describe('{type_name}', () => {{"));
    w.indent();

    w.line("test('roundtrip empty array', () => {");
    w.indent();
    w.line(&format!("const original: {type_name} = [];"));
    w.line(&format!("const decoded = {dname}({fname}(original));"));
    w.line("expect(decoded).toEqual(original);");
    w.dedent();
    w.line("});");

    w.dedent();
    w.line("});");

    let _ = opts; // suppress unused warning
}

// ── Test value helpers ────────────────────────────────────────────────────────

fn ts_default_value(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::Optional => "undefined".into(),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => "[]".into(),
        Occurrence::Required => match ty {
            TypeRef::Primitive(Primitive::Uint | Primitive::Int) =>
                if opts.is_json() { "0".into() } else { "0n".into() },
            TypeRef::Primitive(Primitive::Bool) => "false".into(),
            TypeRef::Primitive(Primitive::Float32 | Primitive::Float16 | Primitive::Float64 | Primitive::Float) => "0".into(),
            TypeRef::Primitive(Primitive::Tstr) => "''".into(),
            TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => "new Uint8Array()".into(),
            TypeRef::Primitive(Primitive::Null | Primitive::Undefined) => "null".into(),
            TypeRef::Named(n) => format!("{{}} as {}", to_pascal_case(n)),
            _ => "null".into(),
        },
    }
}

fn ts_explicit_value(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::Optional => "undefined".into(),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => "[]".into(),
        Occurrence::Required => match ty {
            TypeRef::Primitive(Primitive::Uint) =>
                if opts.is_json() { "42".into() } else { "42n".into() },
            TypeRef::Primitive(Primitive::Int) =>
                if opts.is_json() { "-1".into() } else { "-1n".into() },
            TypeRef::Primitive(Primitive::Bool) => "true".into(),
            TypeRef::Primitive(Primitive::Float32 | Primitive::Float16) => "3.14".into(),
            TypeRef::Primitive(Primitive::Float64 | Primitive::Float)   => "3.14".into(),
            TypeRef::Primitive(Primitive::Tstr) => "'hello'".into(),
            TypeRef::Primitive(Primitive::Bstr | Primitive::Any) =>
                "new Uint8Array([0x01, 0x02])".into(),
            _ => ts_default_value(ty, occ, opts),
        },
    }
}

fn ts_valid_constrained_value(
    constraints: &[Constraint],
    ty:          &TypeRef,
    opts:        &CodegenOptions,
) -> String {
    for c in constraints {
        match c {
            Constraint::SizeExact(n) => match ty {
                TypeRef::Primitive(Primitive::Tstr) =>
                    return format!("'a'.repeat({})", n),
                TypeRef::Primitive(Primitive::Bstr) =>
                    return format!("new Uint8Array({})", n),
                _ => {}
            },
            Constraint::ValueRangeInt { min, .. } => {
                if let Some(lo) = min {
                    return if opts.is_json() { format!("{lo}") } else { format!("{lo}n") };
                }
            }
            Constraint::ValueRangeUint { min, .. } => {
                if let Some(lo) = min {
                    return if opts.is_json() { format!("{lo}") } else { format!("{lo}n") };
                }
            }
            _ => {}
        }
    }
    ts_default_value(ty, &Occurrence::Required, opts)
}

fn ts_invalid_constrained_value(
    constraints: &[Constraint],
    ty:          &TypeRef,
    opts:        &CodegenOptions,
) -> String {
    for c in constraints {
        match c {
            Constraint::SizeExact(n) => match ty {
                TypeRef::Primitive(Primitive::Tstr) =>
                    return format!("'a'.repeat({} + 1) as any", n),
                TypeRef::Primitive(Primitive::Bstr) =>
                    return format!("new Uint8Array({} + 1) as any", n),
                _ => {}
            },
            Constraint::ValueRangeInt { min, .. } => {
                if let Some(lo) = min {
                    return if opts.is_json() {
                        format!("{} as any", lo - 1)
                    } else {
                        format!("{}n as any", lo - 1)
                    };
                }
            }
            Constraint::ValueRangeUint { min, .. } => {
                if let Some(lo) = min {
                    if *lo > 0 {
                        return if opts.is_json() {
                            format!("{} as any", lo - 1)
                        } else {
                            format!("{}n as any", lo - 1)
                        };
                    }
                }
            }
            _ => {}
        }
    }
    "null as any".into()
}
